//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_2554_PaymentMethodsUpdater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WA_2554_PaymentMethodsUpdater.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\NewTariffTable.xml.
        /// </summary>
        internal static string NewTariffTablePath {
            get {
                return ResourceManager.GetString("NewTariffTablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
        /// </summary>
        internal static string Param_Actual_Type {
            get {
                return ResourceManager.GetString("Param_Actual_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paymentMethods.
        /// </summary>
        internal static string Param_Key {
            get {
                return ResourceManager.GetString("Param_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Param_Value_Type {
            get {
                return ResourceManager.GetString("Param_Value_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempProc_PaymentMethodsUpdater_AddFilial.
        /// </summary>
        internal static string ProcName_AddFilial {
            get {
                return ResourceManager.GetString("ProcName_AddFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrUpdateProfileSetting.
        /// </summary>
        internal static string ProcName_AddOrUpdateProfileSetting {
            get {
                return ResourceManager.GetString("ProcName_AddOrUpdateProfileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempProc_PaymentMethodsUpdater_GetParentIdByLogin.
        /// </summary>
        internal static string ProcName_GetParentById {
            get {
                return ResourceManager.GetString("ProcName_GetParentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempProc_PaymentMethodsUpdater_WasFilialProcessed.
        /// </summary>
        internal static string ProcName_WasFilialProcessed {
            get {
                return ResourceManager.GetString("ProcName_WasFilialProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\ProductList.txt.
        /// </summary>
        internal static string ProductsListPath {
            get {
                return ResourceManager.GetString("ProductsListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[TempProc_PaymentMethodsUpdater_AddFilial]
        ///	@filialId uniqueidentifier
        ///AS
        ///BEGIN
        ///	insert into [dbo].[TempTable_PaymentMethodsUpdater_ProcessedFilials] ([FilialId]) values( @filialId)
        ///END
        ///
        ///GRANT EXECUTE ON [dbo].[TempProc_PaymentMethodsUpdater_AddFilial] TO [granted_access] AS [dbo].
        /// </summary>
        internal static string Script_AlterProc_AddFilial {
            get {
                return ResourceManager.GetString("Script_AlterProc_AddFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[TempProc_PaymentMethodsUpdater_GetParentIdByLogin]
        ///	@login nvarchar(250)
        ///AS
        ///BEGIN
        ///	declare @partyId uniqueidentifier
        ///
        ///	select @partyId = partyId from UserList where [LoginName] = @login;
        ///	select parentId 
        ///	from objectInstance oi
        ///	join ObjectHierarchy oh
        ///	on oi.id = oh.NodeID
        ///	where oi.id = @partyId;
        ///	return;
        ///END
        ///
        ///GRANT EXECUTE ON [dbo].[TempProc_PaymentMethodsUpdater_GetParentIdByLogin] TO [granted_access] AS [dbo].
        /// </summary>
        internal static string Script_AlterProc_GetparentIdByLogin {
            get {
                return ResourceManager.GetString("Script_AlterProc_GetparentIdByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[TempProc_PaymentMethodsUpdater_WasFilialProcessed]
        ///	@filialId uniqueidentifier
        ///AS
        ///BEGIN
        ///	select * from [dbo].[TempTable_PaymentMethodsUpdater_ProcessedFilials]  where FilialId = @filialId
        ///END
        ///GRANT EXECUTE ON [dbo].[TempProc_PaymentMethodsUpdater_WasFilialProcessed] TO [granted_access] AS [dbo].
        /// </summary>
        internal static string Script_AlterProc_WasFilialProcessed {
            get {
                return ResourceManager.GetString("Script_AlterProc_WasFilialProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N&apos;[dbo].[TempProc_PaymentMethodsUpdater_AddFilial]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///      EXEC(&apos;CREATE PROCEDURE [dbo].[TempProc_PaymentMethodsUpdater_AddFilial] AS&apos;)
        ///
        ///.
        /// </summary>
        internal static string Script_CreateProc_AddFilial {
            get {
                return ResourceManager.GetString("Script_CreateProc_AddFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N&apos;[dbo].[TempProc_PaymentMethodsUpdater_GetParentIdByLogin]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///      EXEC(&apos;CREATE PROCEDURE [dbo].[TempProc_PaymentMethodsUpdater_GetParentIdByLogin] AS&apos;)
        ///
        ///.
        /// </summary>
        internal static string Script_CreateProc_GetparentIdByLogin {
            get {
                return ResourceManager.GetString("Script_CreateProc_GetparentIdByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N&apos;[dbo].[TempProc_PaymentMethodsUpdater_WasFilialProcessed]&apos;) AND TYPE IN (N&apos;P&apos;, N&apos;PC&apos;))
        ///      EXEC(&apos;CREATE PROCEDURE [dbo].[TempProc_PaymentMethodsUpdater_WasFilialProcessed] AS&apos;)
        ///
        ///.
        /// </summary>
        internal static string Script_CreateProc_WasFilialProcessed {
            get {
                return ResourceManager.GetString("Script_CreateProc_WasFilialProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[TempTable_PaymentMethodsUpdater_ProcessedFilials]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[TempTable_PaymentMethodsUpdater_ProcessedFilials](
        ///	[FilialId] uniqueidentifier PRIMARY KEY
        ///)
        ///END.
        /// </summary>
        internal static string Script_CreateTable_Filials {
            get {
                return ResourceManager.GetString("Script_CreateTable_Filials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop procedure [dbo].[TempProc_PaymentMethodsUpdater_AddFilial].
        /// </summary>
        internal static string Script_DropProc_AddFilial {
            get {
                return ResourceManager.GetString("Script_DropProc_AddFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop procedure [dbo].[TempProc_PaymentMethodsUpdater_GetParentIdByLogin].
        /// </summary>
        internal static string Script_DropProc_GetParentIdByLogin {
            get {
                return ResourceManager.GetString("Script_DropProc_GetParentIdByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop procedure [dbo].[TempProc_PaymentMethodsUpdater_WasFilialProcessed].
        /// </summary>
        internal static string Script_DropProc_WasFilialProcessed {
            get {
                return ResourceManager.GetString("Script_DropProc_WasFilialProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop table [dbo].[TempTable_PaymentMethodsUpdater_ProcessedFilials].
        /// </summary>
        internal static string Script_DropTable_Filials {
            get {
                return ResourceManager.GetString("Script_DropTable_Filials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempTable_PaymentMethodsUpdater_ProcessedFilials.
        /// </summary>
        internal static string TableName_Filials {
            get {
                return ResourceManager.GetString("TableName_Filials", resourceCulture);
            }
        }
    }
}
